### ISSUE TITLE
cesium 类型模块 怎么全局导入的？

### ISSUE THREAD

**Issue by youpengcheng** [hawk86104/vue3-ts-cesium-map-show#2]

**Comment by hawk86104** [comment]
有很多种方式，本项目因为更改了cesium的一些代码，所以直接全局引用的
<img width="1306" alt="image" src="https://github.com/hawk86104/vue3-ts-cesium-map-show/assets/29882682/596a1322-fd62-4d6f-8795-2417207fbe95">

**Comment by hawk86104** [comment]
有什么更多的关于gis 或者 webgl的问题，可以通过我们这个开源webgl社区 提问和搜索。有达人会提供帮助
https://www.icegl.cn/ask

**Comment by Guolipeng666** [comment]
>


> 有什么更多的关于gis 或者 webgl的问题，可以通过我们这个开源webgl社区 提问和搜索。有达人会提供帮助 https://www.icegl.cn/ask

大佬，没想到两年了你还会回复，可以开放一下后台源码代码么o(╥﹏╥)o

**Comment by hawk86104** [comment]
https://gitee.com/hawk86104/vue3-ts-cesium-map-show-backend
我都迁移到gitee上了 不好意思，没在这里跟新了

**Comment by Guolipeng666** [comment]
> https://gitee.com/hawk86104/vue3-ts-cesium-map-show-backend 我都迁移到gitee上了 不好意思，没在这里跟新了
好的
感谢大佬
